### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by kaustav202** [segfault-00/Youtube-Clone#4]
The UI of homepage could be improved with proper spacing between videos

**Comment by kaustav202** [comment]
I'd like to work on it @segfault-00

**Comment by segfault-00** [comment]
> I'd like to work on it @segfault-00

do it whatever you want to do improve

**Comment by kaustav202** [comment]
@segfault-00 why was it closed with someone else's pr when I was assigned the same ??

**Comment by kaustav202** [comment]
This isn't a good community practice

**Comment by kaustav202** [comment]
You should respect contributor's time
